/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StateRouteImport } from './routes/state'
import { Route as NgfRouteImport } from './routes/ngf'
import { Route as IndexRouteImport } from './routes/index'

const StateRoute = StateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => rootRouteImport,
} as any)
const NgfRoute = NgfRouteImport.update({
  id: '/ngf',
  path: '/ngf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ngf': typeof NgfRoute
  '/state': typeof StateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ngf': typeof NgfRoute
  '/state': typeof StateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ngf': typeof NgfRoute
  '/state': typeof StateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ngf' | '/state'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ngf' | '/state'
  id: '__root__' | '/' | '/ngf' | '/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NgfRoute: typeof NgfRoute
  StateRoute: typeof StateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/state': {
      id: '/state'
      path: '/state'
      fullPath: '/state'
      preLoaderRoute: typeof StateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngf': {
      id: '/ngf'
      path: '/ngf'
      fullPath: '/ngf'
      preLoaderRoute: typeof NgfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NgfRoute: NgfRoute,
  StateRoute: StateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
